name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: windows
            os: windows-2022
            target: windows-x86_64
          - build: macos
            os: macos-14
            target: macos-arm64
          - build: macos
            os: macos-13
            target: macos-x86_64
          - build: ubuntu
            os: ubuntu-22.04
            target: ubuntu-x86_64
    
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"

      - name: Build
        shell: bash
        run: |
          pip install pyinstaller
          pip install -e ".[cli]"
          pyinstaller rembg.spec

      - name: Version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Compression
        shell: bash
        run: |
          target_file="rembg-${{ env.VERSION }}-${{ matrix.target }}"
          7z a $target_file.zip ./dist/rembg/*
          echo "ASSET=$target_file.zip" >> $GITHUB_ENV

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
